# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/vokfra/Desktop/pysidetest/qrcodefeedbackscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 640)
        Form.setStyleSheet("\n"
"background: #FFFFFF;")
        self.dateLabel1 = QtWidgets.QLabel(Form)
        self.dateLabel1.setGeometry(QtCore.QRect(760, 20, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        self.dateLabel1.setFont(font)
        self.dateLabel1.setStyleSheet("color: black;\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"text-align: center;\n"
"")
        self.dateLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel1.setObjectName("dateLabel1")
        self.timeLabel1 = QtWidgets.QLabel(Form)
        self.timeLabel1.setGeometry(QtCore.QRect(20, 20, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        self.timeLabel1.setFont(font)
        self.timeLabel1.setStyleSheet("color: black;\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: 500;")
        self.timeLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel1.setObjectName("timeLabel1")
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(720, 510, 231, 119))
        self.frame_5.setMinimumSize(QtCore.QSize(231, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(0)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setLineWidth(0)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setContentsMargins(-1, -1, 12, -1)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: #939191;\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: 500;")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_7.addWidget(self.label_17, 0, QtCore.Qt.AlignRight)
        self.phoneLabel1_3 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        self.phoneLabel1_3.setFont(font)
        self.phoneLabel1_3.setStyleSheet("color: black;\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"\n"
"\n"
"")
        self.phoneLabel1_3.setObjectName("phoneLabel1_3")
        self.verticalLayout_7.addWidget(self.phoneLabel1_3, 0, QtCore.Qt.AlignRight)
        self.mailLabel1_3 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.mailLabel1_3.setFont(font)
        self.mailLabel1_3.setStyleSheet("color: black;\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"")
        self.mailLabel1_3.setObjectName("mailLabel1_3")
        self.verticalLayout_7.addWidget(self.mailLabel1_3, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_5.addWidget(self.frame_8)
        self.label_16 = QtWidgets.QLabel(self.frame_5)
        self.label_16.setMaximumSize(QtCore.QSize(30, 30))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("/Users/vokfra/Desktop/pysidetest/../../Downloads/Icon/Outline/chat-alt.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(540, 250, 50, 50))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/vokfra/Desktop/pysidetest/../../Downloads/Green Tick.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.qrFrame1 = QtWidgets.QFrame(Form)
        self.qrFrame1.setGeometry(QtCore.QRect(390, 110, 180, 180))
        self.qrFrame1.setMinimumSize(QtCore.QSize(0, 0))
        self.qrFrame1.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    width: 178.333px;\n"
"    height: 168.333px;\n"
"    border-radius: 11.118px;\n"
"    border: 3.243px solid #8FB3D1;\n"
"}\n"
"\n"
"QFrame > QLabel {\n"
"    border: none;\n"
"}\n"
"")
        self.qrFrame1.setFrameShape(QtWidgets.QFrame.Box)
        self.qrFrame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.qrFrame1.setLineWidth(2)
        self.qrFrame1.setMidLineWidth(-1)
        self.qrFrame1.setObjectName("qrFrame1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.qrFrame1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_20 = QtWidgets.QLabel(self.qrFrame1)
        self.label_20.setEnabled(True)
        self.label_20.setMaximumSize(QtCore.QSize(147, 147))
        self.label_20.setStyleSheet("")
        self.label_20.setLineWidth(0)
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("/Users/vokfra/Desktop/pysidetest/../../Downloads/Device.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_6.addWidget(self.label_20)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(204, 300, 551, 181))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setEnabled(True)
        self.label_18.setMinimumSize(QtCore.QSize(0, 90))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(32)
        font.setBold(True)
        font.setItalic(False)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: #003873;\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: 600;")
        self.label_18.setLineWidth(0)
        self.label_18.setScaledContents(True)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setIndent(0)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_8.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: black;\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: 0.8;\n"
"")
        self.label_19.setLineWidth(0)
        self.label_19.setMidLineWidth(3)
        self.label_19.setTextFormat(QtCore.Qt.RichText)
        self.label_19.setScaledContents(True)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setWordWrap(True)
        self.label_19.setIndent(0)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_8.addWidget(self.label_19)
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(540, 250, 50, 50))
        self.label_21.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("/Users/vokfra/Desktop/pysidetest/../../Downloads/Red Cross.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.dateLabel1.raise_()
        self.timeLabel1.raise_()
        self.frame_5.raise_()
        self.qrFrame1.raise_()
        self.label.raise_()
        self.frame.raise_()
        self.label_21.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dateLabel1.setText(_translate("Form", "30 June 2023 "))
        self.timeLabel1.setText(_translate("Form", "10:28 AM"))
        self.label_17.setText(_translate("Form", "For support"))
        self.phoneLabel1_3.setText(_translate("Form", "83 3003 1001"))
        self.mailLabel1_3.setText(_translate("Form", "help@kopyfi.com"))
        self.label_18.setText(_translate("Form", "QR Code Scanning Successful"))
        self.label_19.setText(_translate("Form", "Your printing request has been received, and the printing process will start shortly. Please wait while your document is being printed.\n"
""))
