# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/vokfra/Desktop/pysidetest/welcomescreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 640)
        Form.setStyleSheet("\n"
"background: #EAF3FC;")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-10, 70, 353, 503))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/vokfra/Desktop/pysidetest/../../Downloads/welcomekioskimage.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(360, 140, 491, 181))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setEnabled(True)
        self.label_5.setMinimumSize(QtCore.QSize(0, 90))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(73)
        font.setBold(True)
        font.setItalic(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #003873;\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: 700;")
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: black;\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: 0.8;\n"
"")
        self.label_4.setLineWidth(0)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setScaledContents(True)
        self.label_4.setWordWrap(True)
        self.label_4.setIndent(0)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.qrFrame1 = QtWidgets.QFrame(Form)
        self.qrFrame1.setGeometry(QtCore.QRect(800, 380, 161, 168))
        self.qrFrame1.setMinimumSize(QtCore.QSize(0, 0))
        self.qrFrame1.setStyleSheet("background-color: white;\n"
"border: 1px solid white;\n"
"border-bottom-left-radius: 20px;\n"
"border-top-left-radius: 20px;\n"
"width: 178.333px;\n"
"height: 168.333px;")
        self.qrFrame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.qrFrame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.qrFrame1.setObjectName("qrFrame1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.qrFrame1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.qrFrame1)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: black;\n"
"font-family: Poppins;\n"
"font-weight: 600;\n"
"\n"
"\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.frame_3 = QtWidgets.QFrame(self.qrFrame1)
        self.frame_3.setStyleSheet("    background-color: white;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setEnabled(True)
        self.label_2.setMaximumSize(QtCore.QSize(91, 91))
        self.label_2.setStyleSheet("width: 91.528px;\n"
"height: 91.528px;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/Users/vokfra/Desktop/pysidetest/../../Downloads/dummyQRCode.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setMaximumSize(QtCore.QSize(10, 20))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("/Users/vokfra/Desktop/pysidetest/../../Downloads/Icon.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(364, 540, 231, 119))
        self.frame_5.setMinimumSize(QtCore.QSize(231, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(0)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setMaximumSize(QtCore.QSize(30, 30))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("/Users/vokfra/Desktop/pysidetest/../../Downloads/Icon/Outline/chat-alt.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: #939191;\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: 500;")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.phoneLabel1 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        self.phoneLabel1.setFont(font)
        self.phoneLabel1.setStyleSheet("color: black;\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"\n"
"\n"
"")
        self.phoneLabel1.setObjectName("phoneLabel1")
        self.verticalLayout_3.addWidget(self.phoneLabel1)
        self.mailLabel1 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.mailLabel1.setFont(font)
        self.mailLabel1.setStyleSheet("color: black;\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"")
        self.mailLabel1.setObjectName("mailLabel1")
        self.verticalLayout_3.addWidget(self.mailLabel1)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.dateLabel1 = QtWidgets.QLabel(Form)
        self.dateLabel1.setGeometry(QtCore.QRect(760, 20, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        self.dateLabel1.setFont(font)
        self.dateLabel1.setStyleSheet("color: black;\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"text-align: center;\n"
"")
        self.dateLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel1.setObjectName("dateLabel1")
        self.timeLabel1 = QtWidgets.QLabel(Form)
        self.timeLabel1.setGeometry(QtCore.QRect(20, 20, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        self.timeLabel1.setFont(font)
        self.timeLabel1.setStyleSheet("color: black;\n"
"font-family: Poppins;\n"
"font-style: normal;\n"
"font-weight: 500;")
        self.timeLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel1.setObjectName("timeLabel1")
        self.frame.raise_()
        self.qrFrame1.raise_()
        self.frame_5.raise_()
        self.label.raise_()
        self.dateLabel1.raise_()
        self.timeLabel1.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Welcome."))
        self.label_4.setText(_translate("Form", "Scan the QR code linked to your \n"
"order using the Kopyfi app to begin."))
        self.label_3.setText(_translate("Form", "Scan QR CODE"))
        self.label_12.setText(_translate("Form", "For support"))
        self.phoneLabel1.setText(_translate("Form", "83 3003 1001"))
        self.mailLabel1.setText(_translate("Form", "help@kopyfi.com"))
        self.dateLabel1.setText(_translate("Form", "30 June 2023 "))
        self.timeLabel1.setText(_translate("Form", "10:28 AM"))
